apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapp-ui
  template:
    metadata:
      labels:
        app: reactapp-ui
    spec:
      containers:
      - name: reactapp-ui
        image: sachinlakshan/reactapp-ui:local # CI will overwrite this
        ports:
        - containerPort: 80