apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapp-ui
  template:
    metadata:
      labels:
        app: reactapp-ui
    spec:
      containers:
      - name: reactapp-ui
        image: eric7767/reactapp-ui:a186cfeb7cc73fbce19c726bf1bd8f435f71419f
        ports:
        - containerPort: 80